language: go

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -t -v ./...

script:
  - go test -v -race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)