language: go

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: false

env:
  CODECOV_TOKEN="a7f4f4ac-498f-45a6-9938-85425a7828aa"

# Anything in before_script that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash.
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
  - go get github.com/fzipp/gocyclo


before_install:
  - go get -t -v ./...

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
  - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go test -race -coverprofile=coverage.txt -covermode=atomic  # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - golangci-lint run
  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions


after_success:
  - bash <(curl -s https://codecov.io/bash)