language: go

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -t -v ./...

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - golangci-lint run
  - go test -v -race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)