language: go

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: false

env:
  CODECOV_TOKEN="a7f4f4ac-498f-45a6-9938-85425a7828aa"

before_install:
  - go get -t -v ./...

script:
  - go test -v -race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov