appname: enigma
database:
  db_username: "cienciaArgentinaDev"
  db_port: "3306"
server:
  server_port: ":8080"
microservices:
  base_url: "localhost:8080"
  user_endpoints:
    base_resource: "/users"
    login: "/login"
    register: "/"
    send_confirmation_email: "/sendconfirmationemail"
    confirm_email: "/confirmemail"
  email_sender_addr: "http://localhost:8081"
  email_sender_endpoints:
    email_sender_send_email: "/email"
