appname: enigma

database:
  db_username: "root"
  db_port: "3306"

server:
  server_port: ":8080"

argonparams:
  memory: 256
  iterations: 1
  parallelism: 1
  salt_length: 32
  key_length: 32

microservices:
  base_url: "localhost:8080"
  user_endpoints:
    base_resource: "/users"
    login: "/login"
    register: "/"
    send_confirmation_email: "/sendconfirmationemail"
    confirm_email: "/confirmemail"
    send_password_reset: "/sendpasswordreset"
  email_sender_addr: "http://localhost:8081"
  email_sender_endpoints:
    email_sender_send_email: "/email"
